#!/usr/bin/env node
/*
 * make-dev.js — generate app/dev.html from app/dashboard.html
 *
 * app/dev.html is a BUILD OUTPUT. Never edit it by hand; every edit belongs in
 * app/dashboard.html (on whatever branch you're working on) and then you re-run
 * this. It exists for one reason: GitHub Pages only serves `main`, so a feature
 * branch can't be opened on a real iPhone, and every hard bug this project has
 * hit (viewport, header haze, blocked storage, the service worker) was only
 * visible on a real device.
 *
 * Four transforms, each guarding against a specific way a dev build on Kevin's
 * own phone could damage his real data or mislead a test:
 *
 *   1. localStorage namespace — dev reads/writes `dev::` prefixed keys only.
 *      Implemented as a façade over the real localStorage rather than a rename
 *      of the 33 known keys, because the app already uses at least one
 *      un-prefixed key (`installDismissed`) and in-progress features will add
 *      more. A façade cannot miss a key that didn't exist when it was written.
 *   2. Service worker disabled + any existing registration torn down. sw.js is
 *      scoped at the site root, so it will happily cache dev.html and then
 *      serve a stale build back during the next test.
 *   3. Update check neutered. Dev carries a higher APP_VERSION than the live
 *      version.json, so the real check would report an "update" and try to walk
 *      the tester through a data-migrating reload.
 *   4. noindex + a visible DEV badge, so dev never lands in search results and
 *      is never mistaken for prod in a tab switcher.
 *
 * CRLF is preserved on the way out — the repo's working copy is CRLF and a
 * normalized write would show every line as changed.
 */

const fs = require('fs');
const path = require('path');

const SRC = process.argv[2] || 'app/dashboard.html';
const OUT = process.argv[3] || 'app/dev.html';

const SHIM = `
<!-- ═══ DEV BUILD — generated by tools/make-dev.js, do not edit ═══ -->
<meta name="robots" content="noindex,nofollow">
<script>
(function () {
  'use strict';
  var NS = 'dev::';

  /* ── 1. Storage isolation ───────────────────────────────────────────────
     Every key this build touches is prefixed, so a half-built schema can
     never overwrite the real debt data sitting in this same browser. The
     façade also swallows the case where storage is unavailable entirely,
     matching how the app itself probes for it (_storageOK).              */
  try {
    var real = window.localStorage;
    var probe = '__dev_probe__';
    real.setItem(probe, '1');
    real.removeItem(probe);

    var devStore = {
      getItem: function (k) { return real.getItem(NS + k); },
      setItem: function (k, v) { return real.setItem(NS + k, v); },
      removeItem: function (k) { return real.removeItem(NS + k); },
      key: function (i) {
        var keys = devKeys();
        return i < keys.length ? keys[i].slice(NS.length) : null;
      },
      clear: function () {
        devKeys().forEach(function (k) { real.removeItem(k); });
      }
    };
    Object.defineProperty(devStore, 'length', {
      get: function () { return devKeys().length; }
    });

    function devKeys() {
      var out = [];
      for (var i = 0; i < real.length; i++) {
        var k = real.key(i);
        if (k && k.indexOf(NS) === 0) out.push(k);
      }
      return out;
    }

    Object.defineProperty(window, 'localStorage', {
      get: function () { return devStore; },
      configurable: true
    });
  } catch (e) {
    /* Storage blocked. Leave it alone — the app's own _storageOK probe will
       detect this and fall back to its no-storage path, which is itself
       something worth being able to test on a dev build. */
  }

  /* ── 2. Service worker off ──────────────────────────────────────────── */
  if ('serviceWorker' in navigator) {
    try {
      navigator.serviceWorker.getRegistrations().then(function (regs) {
        regs.forEach(function (r) { r.unregister(); });
      }).catch(function () {});
    } catch (e) {}
    try {
      navigator.serviceWorker.register = function () {
        return Promise.reject(new Error('dev build: service worker disabled'));
      };
    } catch (e) {}
    if (window.caches && caches.keys) {
      caches.keys().then(function (names) {
        names.forEach(function (n) { caches.delete(n); });
      }).catch(function () {});
    }
  }

  /* ── 5. Analytics off ───────────────────────────────────────────────────
     Dev sessions would otherwise land in GA4 and Clarity alongside real
     traffic. That matters more than usual right now: the sales and funnel
     numbers being used to decide the $24 price change come out of this
     property, and four weeks of a developer reloading a build would quietly
     inflate them. The tag scripts are blocked at the network level below;
     this stubs the API so any in-app gtag()/clarity() call is a no-op rather
     than a ReferenceError.                                                */
  window.dataLayer = window.dataLayer || [];
  window.gtag = function () {};
  window.clarity = function () {};
  var _origCreate = document.createElement.bind(document);
  document.createElement = function (tag) {
    var el = _origCreate(tag);
    if (String(tag).toLowerCase() === 'script') {
      try {
        Object.defineProperty(el, 'src', {
          get: function () { return this.getAttribute('src') || ''; },
          set: function (v) {
            if (/googletagmanager\\.com|clarity\\.ms/i.test(String(v))) return; // dropped
            this.setAttribute('src', v);
          },
          configurable: true
        });
      } catch (e) {}
    }
    return el;
  };

  /* ── 4. Badge ───────────────────────────────────────────────────────── */
  window.addEventListener('DOMContentLoaded', function () {
    var b = document.createElement('div');
    b.id = 'dev-build-badge';
    b.textContent = 'DEV';
    b.title = 'Development build — separate storage, not your real data';
    b.style.cssText = [
      'position:fixed', 'left:10px', 'bottom:10px', 'z-index:2147483647',
      'font:700 10px/1 system-ui,sans-serif', 'letter-spacing:.12em',
      'padding:5px 8px', 'border-radius:5px', 'pointer-events:none',
      'background:#b45309', 'color:#fff', 'opacity:.85',
      'box-shadow:0 1px 4px rgba(0,0,0,.4)'
    ].join(';');
    document.body.appendChild(b);
  });
})();
</script>
<!-- ═══ end dev shim ═══ -->
`;

function build() {
  const srcPath = path.resolve(SRC);
  if (!fs.existsSync(srcPath)) {
    console.error('ERROR: source not found: ' + srcPath);
    process.exit(1);
  }

  let html = fs.readFileSync(srcPath, 'utf8');
  const hadCRLF = html.indexOf('\r\n') !== -1;
  html = html.replace(/\r\n/g, '\n');

  const checks = [];

  // Transform 1/2/4 — inject the shim as the first thing inside <head>.
  const headMatch = html.match(/<head>/i);
  if (!headMatch) {
    console.error('ERROR: no <head> found — did the source change shape?');
    process.exit(1);
  }
  html = html.replace(/<head>/i, '<head>' + SHIM.replace(/\r\n/g, '\n'));
  checks.push(['shim injected after <head>', html.indexOf('dev-build-badge') !== -1]);

  // Transform 3 — neuter the update check. The app compares serverVersion to
  // APP_VERSION; feeding it APP_VERSION makes it report "you're up to date"
  // instead of trying to migrate the tester onto the live build.
  const FETCH_LINE = "const res = await fetch('/app/version.json?t=' + Date.now());";
  const FETCH_STUB = "const res = { ok: true, json: async () => ({ version: APP_VERSION, notes: ['Development build.'] }) }; // dev: update check disabled";
  const hadFetch = html.indexOf(FETCH_LINE) !== -1;
  html = html.split(FETCH_LINE).join(FETCH_STUB);
  checks.push(['update check neutered', hadFetch]);

  // Transform 5 (static half) — the GA4 tag is a literal <script src> in the
  // markup, so the createElement hook in the shim never sees it. Clarity is
  // injected dynamically and IS caught by the hook.
  const GA_TAG = /<script async src="https:\/\/www\.googletagmanager\.com\/gtag\/js\?id=[^"]*"><\/script>/i;
  const hadGA = GA_TAG.test(html);
  html = html.replace(GA_TAG, '<!-- dev: GA4 tag removed so dev sessions stay out of real analytics -->');
  checks.push(['GA4 tag removed', hadGA]);

  // Title, so the tab is unmistakable in a switcher.
  const hadTitle = /<title>/i.test(html);
  html = html.replace(/<title>([^<]*)<\/title>/i, '<title>[DEV] $1</title>');
  checks.push(['title marked [DEV]', hadTitle]);

  // Manifest — a dev build must not offer to install itself over the real PWA.
  const hadManifest = /<link rel="manifest"/i.test(html);
  html = html.replace(/<link rel="manifest"[^>]*>/i, '<!-- dev: manifest removed so this cannot install over the real PWA -->');
  checks.push(['manifest removed', hadManifest]);

  let failed = false;
  console.log('');
  for (const [label, ok] of checks) {
    console.log('  ' + (ok ? 'ok  ' : 'FAIL') + '  ' + label);
    if (!ok) failed = true;
  }
  console.log('');

  if (failed) {
    console.error('ERROR: a transform did not apply. dashboard.html probably');
    console.error('changed shape around one of the anchors above. Fix the');
    console.error('anchor in tools/make-dev.js rather than shipping a partly-');
    console.error('transformed dev build — a dev build missing its storage');
    console.error('namespace writes straight into real debt data.');
    process.exit(1);
  }

  if (hadCRLF) html = html.replace(/\n/g, '\r\n');
  fs.writeFileSync(path.resolve(OUT), html, 'utf8');

  const ver = (html.match(/APP_VERSION = '([^']*)'/) || [])[1] || '?';
  console.log('  wrote ' + OUT + '  (from v' + ver + ', ' +
              (hadCRLF ? 'CRLF' : 'LF') + ' preserved)');
  console.log('');
}

build();
